on:
  check_suite:
    types: [completed]
name: CI email
jobs:
  sendEmail:
    name: Send email
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - run: echo "CI failed" && false
      if: github.event.check_suite.conclusion != 'neutral' && github.event.check_suite.conclusion != 'success'
