on:
  check_suite:
    types: [completed]
name: CI email
jobs:
  sendEmail:
    name: Send email
    runs-on: ubuntu-latest
    steps:
    - run: echo "CI failed" && false
      if: github.event.check_suite.conclusion != 'neutral' && github.event.check_suite.conclusion != 'success'
